---
# Section 1.4: Positive Definite Systems; Cholesky Decomposition
---

After triangular linear systems, the next easiest type of linear system to solve is the **symmetric positive definite** linear system.

A matrix $A \in \mathbb{R}^{n \times n}$ is **symmetric** if $A = A^T$.

For example,

$$
A = 
\begin{bmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6
\end{bmatrix}
$$

is a symmetric matrix.

A matrix $A \in \mathbb{R}^{n \times n}$ is called **positive definite** if $A$ is symmetric and 

$$
x^T A x > 0, \qquad \text{for all nonzero $x \in \mathbb{R}^n$.}
$$

---

### Exercise:

Let $A = \begin{bmatrix} 2 & -1 \\ -1 & 2 \end{bmatrix}$ and $x = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \neq 0$. Prove that $x^T A x > 0$.

In [1]:
A = [ 2 -1; -1 2 ]

2×2 Matrix{Int64}:
  2  -1
 -1   2

In [23]:
x = randn(2)
@show x
@show x'*A*x;

x = [-0.811444178301137, 1.4725656874448798]
x' * A * x = 8.043592425163956


Let $x$ be a nonzero vector. Then,

\begin{eqnarray}
x^T A x
&=& 
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}^T
\begin{bmatrix} 2 & -1 \\ -1 & 2 \end{bmatrix}
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix} \\
&=& 
\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}^T
\begin{bmatrix} 2x_1 - x_2 \\ -x_1 + 2x_2 \end{bmatrix} \\
&=& x_1(2x_1 - x_2) + x_2(-x_1 + 2x_2) \\
&=& 2x_1^2 - 2 x_1 x_2 + 2x_2^2 \\
&=& x_1^2 + (x_1^2 - 2 x_1 x_2 + x_2^2) + x_2^2 \\
&=& x_1^2 + (x_1 - x_2)^2 + x_2^2 \\
&\ge& x_1^2 + x_2^2 \\
&>& 0,
\end{eqnarray}

since $x$ is a nonzero vector. Therefore, the symmetric matrix $A$ is positive definite.

In [24]:
x'*A*x

8.043592425163956

In [25]:
x[1]^2 + (x[1] - x[2])^2 + x[2]^2

8.043592425163956

---

## Properties of positive definite matrices

(1) If $A$ is positive definite, then $A$ is nonsingular.

(2) If $A$ is positive definite, then $Ax = b$ has a unique solution.

(3) If $A = M^TM$ for some nonsingular $M \in \mathbb{R}^{n \times n}$, then $A$ is positive definite.

(4) $A$ is positive definite $\Longleftrightarrow$ all eigenvalues of $A$ are positive.

In [27]:
using LinearAlgebra

In [28]:
eigvals(A)

2-element Vector{Float64}:
 1.0
 3.0

---
### Exercise:

Prove property (1) and deduce property (2).

#### Proof:

Let $A$ be a symmetric positive definite matrix. Suppose, for the sake of contradiction, that $A$ is singular. Then there is a nonzero vector $x$ such that $Ax = 0$. So we have that $x^T A x = x^T 0 = 0$, which contradicts our assumption that $A$ is positive definite. Therefore, $A$ is nonsingular.

Since $A$ is nonsingular, any linear system $Ax = b$ has a unique solution. $\blacksquare$

---
### Exercise:

Based on property (3), write a `Julia` function `A = randspd(n)` that randomly generates an $n \times n$ symmetric positive definite matrix $A$. Check that the matrix $A$ is positive definite by using property (4).

In [29]:
function randspd(n)
    M = randn(n,n)
    A = M'M
end

randspd (generic function with 1 method)

In [34]:
A = randspd(5)

5×5 Matrix{Float64}:
  1.96438   -1.18838     1.56238    -0.275037   -3.16687
 -1.18838    4.44811     0.566154   -0.0271129   3.46538
  1.56238    0.566154    2.38428    -0.0982263  -3.10933
 -0.275037  -0.0271129  -0.0982263   0.331262   -0.280421
 -3.16687    3.46538    -3.10933    -0.280421    8.73664

In [35]:
eigvals(A)

5-element Vector{Float64}:
  0.0021833211598131265
  0.11872021851575325
  0.950068996529474
  4.158591404816379
 12.635106746345294

In [36]:
n = 5
M = randn(n,n)
eigvals(M)

5-element Vector{ComplexF64}:
 0.2857708205669522 - 1.7414758040084537im
 0.2857708205669522 + 1.7414758040084537im
  1.414478100849271 - 0.325491539998444im
  1.414478100849271 + 0.325491539998444im
 1.7914333483570748 + 0.0im

---

## The Cholesky Decomposition

It turns out that every positive definite matrix $A$ can be written as $A = M^TM$, for some nonsingular matrix $M$.

> ### Cholesky Decomposition Theorem
> Let $A$ be positive definite.
> Then there is a **unique upper-triangular matrix** $R$ with **positive diagonal entries** such that
> $$A = R^T R.$$

We will see a proof of this theorem later.

---

### Exercise:

Computing the Cholesky factor of a random positive definite matrix $A$ using the `Julia` function `cholesky`. Check that the output is correct.

In [37]:
?cholesky

search: cholesky cholesky! Cholesky CholeskyPivoted



```
cholesky(A, Val(false); check = true) -> Cholesky
```

Compute the Cholesky factorization of a dense symmetric positive definite matrix `A` and return a [`Cholesky`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`StridedMatrix`](@ref) or a *perfectly* symmetric or Hermitian `StridedMatrix`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F.L` and `F.U`. The following functions are available for `Cholesky` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), [`logdet`](@ref) and [`isposdef`](@ref).

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

# Examples

```jldoctest
julia> A = [4. 12. -16.; 12. 37. -43.; -16. -43. 98.]
3×3 Matrix{Float64}:
   4.0   12.0  -16.0
  12.0   37.0  -43.0
 -16.0  -43.0   98.0

julia> C = cholesky(A)
Cholesky{Float64, Matrix{Float64}}
U factor:
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.U
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 2.0  6.0  -8.0
  ⋅   1.0   5.0
  ⋅    ⋅    3.0

julia> C.L
3×3 LowerTriangular{Float64, Matrix{Float64}}:
  2.0   ⋅    ⋅
  6.0  1.0   ⋅
 -8.0  5.0  3.0

julia> C.L * C.U == A
true
```

---

```
cholesky(A, Val(true); tol = 0.0, check = true) -> CholeskyPivoted
```

Compute the pivoted Cholesky factorization of a dense symmetric positive semi-definite matrix `A` and return a [`CholeskyPivoted`](@ref) factorization. The matrix `A` can either be a [`Symmetric`](@ref) or [`Hermitian`](@ref) [`StridedMatrix`](@ref) or a *perfectly* symmetric or Hermitian `StridedMatrix`. The triangular Cholesky factor can be obtained from the factorization `F` with: `F.L` and `F.U`. The following functions are available for `CholeskyPivoted` objects: [`size`](@ref), [`\`](@ref), [`inv`](@ref), [`det`](@ref), and [`rank`](@ref). The argument `tol` determines the tolerance for determining the rank. For negative values, the tolerance is the machine precision.

If you have a matrix `A` that is slightly non-Hermitian due to roundoff errors in its construction, wrap it in `Hermitian(A)` before passing it to `cholesky` in order to treat it as perfectly Hermitian.

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

---

```
cholesky(A::SparseMatrixCSC; shift = 0.0, check = true, perm = nothing) -> CHOLMOD.Factor
```

Compute the Cholesky factorization of a sparse positive definite matrix `A`. `A` must be a [`SparseMatrixCSC`](@ref) or a [`Symmetric`](@ref)/[`Hermitian`](@ref) view of a `SparseMatrixCSC`. Note that even if `A` doesn't have the type tag, it must still be symmetric or Hermitian. If `perm` is not given, a fill-reducing permutation is used. `F = cholesky(A)` is most frequently used to solve systems of equations with `F\b`, but also the methods [`diag`](@ref), [`det`](@ref), and [`logdet`](@ref) are defined for `F`. You can also extract individual factors from `F`, using `F.L`. However, since pivoting is on by default, the factorization is internally represented as `A == P'*L*L'*P` with a permutation matrix `P`; using just `L` without accounting for `P` will give incorrect answers. To include the effects of permutation, it's typically preferable to extract "combined" factors like `PtL = F.PtL` (the equivalent of `P'*L`) and `LtP = F.UP` (the equivalent of `L'*P`).

When `check = true`, an error is thrown if the decomposition fails. When `check = false`, responsibility for checking the decomposition's validity (via [`issuccess`](@ref)) lies with the user.

Setting the optional `shift` keyword argument computes the factorization of `A+shift*I` instead of `A`. If the `perm` argument is provided, it should be a permutation of `1:size(A,1)` giving the ordering to use (instead of CHOLMOD's default AMD ordering).

# Examples

In the following example, the fill-reducing permutation used is `[3, 2, 1]`. If `perm` is set to `1:3` to enforce no permutation, the number of nonzero elements in the factor is 6.

```jldoctest
julia> A = [2 1 1; 1 2 0; 1 0 2]
3×3 Matrix{Int64}:
 2  1  1
 1  2  0
 1  0  2

julia> C = cholesky(sparse(A))
SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  5
nnz:     5
success: true

julia> C.p
3-element Vector{Int64}:
 3
 2
 1

julia> L = sparse(C.L);

julia> Matrix(L)
3×3 Matrix{Float64}:
 1.41421   0.0       0.0
 0.0       1.41421   0.0
 0.707107  0.707107  1.0

julia> L * L' ≈ A[C.p, C.p]
true

julia> P = sparse(1:3, C.p, ones(3))
3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
  ⋅    ⋅   1.0
  ⋅   1.0   ⋅
 1.0   ⋅    ⋅

julia> P' * L * L' * P ≈ A
true

julia> C = cholesky(sparse(A), perm=1:3)
SuiteSparse.CHOLMOD.Factor{Float64}
type:    LLt
method:  simplicial
maxnnz:  6
nnz:     6
success: true

julia> L = sparse(C.L);

julia> Matrix(L)
3×3 Matrix{Float64}:
 1.41421    0.0       0.0
 0.707107   1.22474   0.0
 0.707107  -0.408248  1.1547

julia> L * L' ≈ A
true
```

!!! note
    This method uses the CHOLMOD library from SuiteSparse, which only supports doubles or complex doubles. Input matrices not of those element types will be converted to `SparseMatrixCSC{Float64}` or `SparseMatrixCSC{ComplexF64}` as appropriate.

    Many other functions from CHOLMOD are wrapped but not exported from the `Base.SparseArrays.CHOLMOD` module.



In [38]:
n = 5
A = randspd(n)

5×5 Matrix{Float64}:
  3.83519   -1.69009     0.044218    3.75477    0.496562
 -1.69009    1.3782      0.0773687  -1.62612   -0.119435
  0.044218   0.0773687   2.55684    -0.084507   0.712591
  3.75477   -1.62612    -0.084507    6.70871    2.35541
  0.496562  -0.119435    0.712591    2.35541    1.84005

In [39]:
F = cholesky(A)

Cholesky{Float64, Matrix{Float64}}
U factor:
5×5 UpperTriangular{Float64, Matrix{Float64}}:
 1.95837  -0.863013  0.022579   1.9173     0.253559
  ⋅        0.795871  0.121697   0.0358507  0.124883
  ⋅         ⋅        1.59421   -0.0829002  0.433861
  ⋅         ⋅         ⋅         1.73911    1.09294
  ⋅         ⋅         ⋅          ⋅         0.614335

In [40]:
R = F.U

5×5 UpperTriangular{Float64, Matrix{Float64}}:
 1.95837  -0.863013  0.022579   1.9173     0.253559
  ⋅        0.795871  0.121697   0.0358507  0.124883
  ⋅         ⋅        1.59421   -0.0829002  0.433861
  ⋅         ⋅         ⋅         1.73911    1.09294
  ⋅         ⋅         ⋅          ⋅         0.614335

In [41]:
A - R'R

5×5 Matrix{Float64}:
  0.0          2.22045e-16  0.0          0.0  -5.55112e-17
  2.22045e-16  0.0          0.0          0.0   0.0
  0.0          0.0          4.44089e-16  0.0   0.0
  0.0          0.0          0.0          0.0   0.0
 -5.55112e-17  0.0          0.0          0.0   0.0

---

### Exercise:

The function `cholesky` will detect if $A$ is not positive definite. In fact, this is the **most efficient** method for testing if a symmetric matrix is positive definite or not.

See what happens when you give the `cholesky` function a matrix that is symmetric but not positive definite.

In [42]:
n = 5
M = randn(n,n)
A = M + M'

5×5 Matrix{Float64}:
 -1.67549     1.34285    1.6189   -0.0229959  -1.47163
  1.34285    -0.158231   0.95082  -1.64809    -0.127375
  1.6189      0.95082   -1.59807   1.87788     1.03154
 -0.0229959  -1.64809    1.87788   3.81699    -2.02654
 -1.47163    -0.127375   1.03154  -2.02654     0.241032

In [43]:
F = cholesky(A)

LoadError: PosDefException: matrix is not positive definite; Cholesky factorization failed.

In [44]:
eigvals(A)

5-element Vector{Float64}:
 -4.536922292427493
 -2.3820393253734915
  0.5270177355215954
  1.6789340179856265
  5.339247464392662

In [45]:
isposdef(A)

false

In [56]:
isposdef(randspd(n))

true

---

### Exercise:

Let $R$ be the Cholesky factor of a positive definite matrix $A$. 

1. Propose an algorithm for solving $Ax = b$ using the Cholesky factorization $A = R^TR$. Your algorithm should have **two** steps, a forward-substitution and a backward-substitution.

2. What is the flop count of your algorithm?

3. Implement your algorithm in `Julia`. Check that the output is correct.

#### Part 1

Suppose $A$ is symmetric positive definite and that $A = R^TR$ is its Cholesky decomposition. Suppose also that $Ax = b$. Then

$$
R^T R x = b.
$$

Let $z = R x$. Then $R^T z = b$ is a lower triangular linear system, and since the diagonal entries of $R$ are all positive, the matrix $R^T$ is nonsingular. So our algorithm is:

1. Solve $R^T z = b$ for the vector $z$ using forward substitution.
2. Solve $R x = z$ for the vector $x$ using backward substitution.

#### Part 2

Suppose that $A$ is $n \times n$. Then both $R$ and $R^T$ are $n \times n$. Then we have:

1. Solving $R^T z = b$ requires $n^2$ flops.
2. Solving $R x = z$ requires $n^2$ flops.

So, in total, solving $A x = b$ given the Cholesky decomposition of $A$ requires $2 n^2$ flops. Note this is the same flop count as multiplying a $n \times n$ matrix times a vector.

### Part 3

In [59]:
n = 5
A = randspd(n)
xtrue = randn(n)
b = A*xtrue

F = cholesky(A)
R = F.U

# Step 1 (forward substitution)
z = R'\b

# Step 2 (backward substitution)
x = R\z

5-element Vector{Float64}:
 -1.32152531644529
  0.8275283189408019
  0.9748235980121617
  0.7110282330642613
 -0.668775443253583

In [61]:
x - xtrue

5-element Vector{Float64}:
  0.0
  1.4432899320127035e-15
  6.439293542825908e-15
  1.1102230246251565e-15
 -8.881784197001252e-16

---
### Exercise:

Compute the Cholesky factor of $A$ by hand by writing $A = R^T R$ as follows.

$$ 
\begin{bmatrix}
 4 & -2 &  4 \\
-2 & 10 & -2 \\
 4 & -2 &  8 \\
\end{bmatrix} =
\begin{bmatrix}
r_{11} \\
r_{12} & r_{22} \\
r_{13} & r_{23} & r_{33} \\
\end{bmatrix}
\begin{bmatrix}
r_{11} & r_{12} & r_{13} \\
       & r_{22} & r_{23} \\
       &        & r_{33} \\
\end{bmatrix}
$$

Multiplying the two matrices on the rhs gives us

$$
\begin{bmatrix}
 4 & -2 &  4 \\
-2 & 10 & -2 \\
 4 & -2 &  8 \\
\end{bmatrix} =
\begin{bmatrix}
r_{11}^2 & r_{11} r_{12} & r_{11} r_{13} \\
r_{11} r_{12} & r_{12}^2 + r_{22}^2 & r_{12} r_{13} + r_{22} r_{23} \\
r_{11} r_{13} & r_{12} r_{13} + r_{22} r_{23} & r_{13}^2 + r_{23}^2 + r_{33}^2
\end{bmatrix}.
$$

Then we have:

1. $r_{11}^2 = 4 \implies r_{11} = 2$
2. $r_{11} r_{12} = -2 \implies 2 r_{12} = -2 \implies r_{12} = -1$
3. $r_{11} r_{13} = 4 \implies 2 r_{13} = 4 \implies r_{13} = 2$
4. $r_{12}^2 + r_{22}^2 = 10 \implies 1 + r_{22}^2 = 10 \implies r_{22} = 3$
5. $r_{12} r_{13} + r_{22} r_{23} = -2 \implies -2 + 3 r_{23} = -2 \implies r_{23} = 0$
6. $r_{13}^2 + r_{23}^2 + r_{33}^2 = 8 \implies 4 + 0 + r_{33}^2 = 8 \implies r_{33} = 2$

Therefore,

$$
R = \begin{bmatrix}
2 & -1 & 2 \\
  &  3 & 0 \\
  &    & 2
  \end{bmatrix}.
  $$

In [62]:
R = [ 2 -1 2; 0 3 0; 0 0 2]

3×3 Matrix{Int64}:
 2  -1  2
 0   3  0
 0   0  2

In [63]:
R'R

3×3 Matrix{Int64}:
  4  -2   4
 -2  10  -2
  4  -2   8

In [65]:
A = [
    4 -2 4
    -2 10 -2
    4 -2 8 ]

3×3 Matrix{Int64}:
  4  -2   4
 -2  10  -2
  4  -2   8

---

### General Inner-Product Cholesky Formula

The general formulas for the entries $r_{ij}$ of the Cholesky factor $R$ of a positive definite matrix $A$ are given by

$$
\begin{align}
r_{ii} &= \sqrt{a_{ii} - \sum_{k=1}^{i-1} r_{ki}^2}, \\
r_{ij} &= \left(a_{ij} - \sum_{k=1}^{i-1} r_{ki} r_{kj}\right)\bigg/r_{ii}, \qquad j = i+1, \ldots, n. \\
\end{align}
$$

---

### Exercise:

Complete the following `Julia` function for the inner-product version of Cholesky's Algorithm.

In [ ]:
function chol_ip(A::Symmetric)
        
    # Initialize R to be the upper-triangular part of A
    R = UpperTriangular(copy(A))

    n = size(A, 1)

    for i = 1:n
        # R[i,i] = sqrt(A[i,i] - sum_{k=1}^{i-1} R[k,i]^2)
        
        # R[i,j] = (A[i,j] - sum_{k=1}^{i-1} R[k,i]*R[k,j]) / R[i,i]
        
    end
    
    return R
end

---

### Exercise:

Develop the **Outer-Product Form of Cholesky's Algorithm** by partitioning $A = R^TR$ as:

$$
\begin{bmatrix}
a_{11} & b^T \\
b & \hat{A} \\
\end{bmatrix} 
= 
\begin{bmatrix}
r_{11} & 0 \\
s & \hat{R}^T \\
\end{bmatrix}
\begin{bmatrix}
r_{11} & s^T \\
0 & \hat{R} \\
\end{bmatrix}.
$$

1. Use block-matrix multiplication to multiply the matrices $R^T$ and $R$.
2. Based on the equations from part (1), derive a recursive algorithm for computing $R$.

---

### Exercise:

Complete the following `Julia` function for the recursive version of Cholesky's Algorithm.

In [ ]:
function chol_rop(A::Symmetric)

    n = size(A, 1)

    # Initialize R = 0 and the same size and datatype as A
    R = UpperTriangular(zeros(n, n))
    
    #######################
    # Your code goes here #
    #######################
    
    return R
    
end

---

### Exercise:

Develop the **Bordered Form of Cholesky's Algorithm** by partitioning $A = R^TR$ as:

$$
\begin{bmatrix}
\hat{A} & c \\
c^T & a_{nn} \\
\end{bmatrix} 
= 
\begin{bmatrix}
\hat{R}^T & 0 \\
h^T & r_{nn} \\
\end{bmatrix}
\begin{bmatrix}
\hat{R} & h \\
0 & r_{nn} \\
\end{bmatrix}
$$

1. Use block-matrix multiplication to multiply the matrices $R^T$ and $R$.
2. Based on the equations from part (1), derive a recursive algorithm for computing $R$.
3. Based on your recursive algorithm, determine the number of flops for computing the Cholesky decomposition of an $n \times n$ positive definite matrix $A$.

---

## Proof of the Cholesky Decomposition Theorem

> ### Cholesky Decomposition Theorem
> Let $n$ be a positive integer. If $A$ is an $n \times n$ positive definite matrix, then there is a **unique $n \times n$ upper-triangular matrix** $R$ with **positive diagonal entries** such that
> $$A = R^T R.$$

We will prove this theorem using mathematical induction, based on the following partitioning.

$$
\begin{bmatrix}
\hat{A} & c \\
c^T & a_{nn} \\
\end{bmatrix} 
= 
\begin{bmatrix}
\hat{R}^T & 0 \\
h^T & r_{nn} \\
\end{bmatrix}
\begin{bmatrix}
\hat{R} & h \\
0 & r_{nn} \\
\end{bmatrix}
$$

First we need to prove the following lemma.

> ### Lemma
> Let $A$ be positive definite and partitioned as
>
> $$
A = 
\begin{bmatrix}
A_{11} & A_{12} \\
A_{21} & A_{22}
\end{bmatrix}
$$
>
>where $A_{11} \in \mathbb{R}^{n_1 \times n_1}$ and $A_{22} \in \mathbb{R}^{n_2 \times n_2}$. Then $A_{11}$ and $A_{22}$ are positive definite.

---
### Exercise:

Prove the lemma.

---
### Exercise:

Use the following steps to prove the theorem.

1. Prove that the theorem is true for $n = 1$. This is the _base case_.
2. Suppose that the theorem is true for $n = k$. This is the _induction hypothesis_.
3. Let $n = k+1$ and let $A$ be an $n \times n$ positive definite matrix.
4. Show that there is a unique $n \times n$ upper-triangular matrix $R$ with positive diagonal entries such that $A = R^T R$ by considering the following partitioning of $A = R^T R$,
 $$
\begin{bmatrix}
\hat{A} & c \\
c^T & a_{nn} \\
\end{bmatrix} 
= 
\begin{bmatrix}
\hat{R}^T & 0 \\
h^T & r_{nn} \\
\end{bmatrix}
\begin{bmatrix}
\hat{R} & h \\
0 & r_{nn} \\
\end{bmatrix},
$$
 and showing that there exist unique $\hat{R}$, $h$, and $r_{nn}$ that satisfy this equation.

---